framework:
    validation:
        enable_attributes: true
        mapping:
            paths:
                - '%kernel.project_dir%/config/validation.yaml'

when@test:
    framework:
        validation:
            not_compromised_password: false
